apiVersion: v1
kind: Secret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
type: Opaque
data:
  # RDS
  AUTH_DATABASE_URL: ${AUTH_DATABASE_URL_BASE64_ENCODED}
  FLAG_DATABASE_URL: ${FLAG_DATABASE_URL_BASE64_ENCODED}
  TARGETING_DATABASE_URL: ${TARGETING_DATABASE_URL_BASE64_ENCODED}

  # APPS
  MASTER_KEY: ${MASTER_KEY_BASE64_ENCODED}

  # Redis
  REDIS_URL: ${REDIS_URL_BASE64_ENCODED}

  # SQS
  AWS_REGION: ${AWS_REGION_BASE64_ENCODED}
  AWS_SQS_URL: ${AWS_SQS_URL_BASE64_ENCODED}

  # DynamoDB
  AWS_DYNAMODB_TABLE: ${AWS_DYNAMODB_TABLE_BASE64_ENCODED}
