apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: analytics-service
C1488046339.dkr.ecr.us-east-1.amazonaws.com/togglemaster/analytics:1cbeaad85ce3bb96c690b2e25fc96834c4ea4ea1
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          env:
            - name: PORT
              value: "8005"
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                secretKeyRef:
                  name: togglemaster-secrets
                  key: AWS_DYNAMODB_TABLE
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: togglemaster-secrets
                  key: AWS_SQS_URL
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: togglemaster-secrets
                  key: AWS_REGION
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 8
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - port: 8005
      targetPort: 8005
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-service-hpa
  namespace: togglemaster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 8
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
        - type: Pods
          value: 3
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 20
