apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: togglemaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: evaluation-service
          image: 031488046339.dkr.ecr.us-east-1.amazonaws.com/togglemaster/evaluation:4ca6f06f8aca51f63ee8c16fe4744c6c4be935d0
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: PORT
              value: "8004"
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: togglemaster-runtime
                  key: SERVICE_API_KEY
                  optional: true
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: togglemaster-secrets
                  key: REDIS_URL
            - name: FLAG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: FLAG_SERVICE_URL
            - name: TARGETING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: TARGETING_SERVICE_URL
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: togglemaster-secrets
                  key: AWS_SQS_URL
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: togglemaster-secrets
                  key: AWS_REGION
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: togglemaster
spec:
  type: ClusterIP
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: evaluation-service-hpa
  namespace: togglemaster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: evaluation-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
        - type: Pods
          value: 3
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 20
